name: Create and publish a Docker image
on:
  push:
    branches: ['2.11.2-fork']
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  KO_DEFAULTBASEIMAGE: docker.io/huacnlee/gobackup:v2.11.2
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
      - uses: ko-build/setup-ko@v0.6
      - name: "Build Web"
        run: |
          cd web
          yarn && yarn build
      - run: ko build --platform=all
