name: Create and publish a Docker image
on:
  push:
    branches: ['2.11.2-fork']
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  KO_DEFAULTBASEIMAGE: ghcr.io/${{ github.repository }}:baseimage
jobs:
  baseimage:
    name: Baseimage
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          file: Dockerfile.baseimage
          tags: |
            ghcr.io/${{ github.repository }}:baseimage
  publish:
    needs: baseimage
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
      - uses: ko-build/setup-ko@v0.6
      - name: "Build Web"
        run: |
          cd web
          yarn && yarn build
      - run: ko build --platform=all
